// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqwmadeuwihupezjwxmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxd21hZGV1d2lodXBlemp3eG1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwMzkzOTksImV4cCI6MjA2MjYxNTM5OX0.yoVNF9OK4Ocrt4LY6Q8WRiyqICaSIbWlcP6zsKiujSw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);